# Generated by Django 5.2.13 on 2026-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='totalAmount',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('A', 'Approved'), ('C', 'Completed')], default='P', max_length=1),
        ),
    ]
