# Generated by Django 5.2.15 on 2026-07-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_alter_orders_status_productsimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsimage',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('A', 'Approved'), ('F', 'Failed')], default='P', max_length=1),
        ),
    ]
