# Generated by Django 5.2.17 on 2026-09-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_alter_orders_options_orders_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimage',
            name='image',
            field=models.URLField(),
        ),
    ]
