# Generated by Django 5.2.15 on 2026-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='delivery_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='loyalty_points',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
