name: Abaya shop CI CD pipeline
on:
  push:
    branches:
      - main
      - develop
jobs:
    check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List Files
        run: ls -la
      - name: Echo Message
        run: echo "Hello, this is a CI/CD pipeline for Abaya shop!"
