name: Abaya shop CI CD pipeline
on:
  push:
    branches:
      - main
      - develop
jobs:
    check:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: backend
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: build docker image
          run: docker build -t abayashop .
        - name: run container
          run: docker run -d -p 8000:8000 --name abayashop-container abayashop
        - name: wait for app
          run: sleep 5

        - name: List Files
          run: ls -la
        - name: Echo Message
          run: echo "Hello, this is a CI/CD pipeline for Abaya shop!"
