# Generated by Django 5.2.15 on 2026-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_rename_product_productsimage_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('F', 'Failed'), ('C', 'Completed'), ('P', 'Pending'), ('A', 'Approved')], default='P', max_length=1),
        ),
    ]
